experiment_name: medical
output_dir: ""
save_embeddings: False 
resume_id:


data:
  work_dir: 
  label_name: "Isup Grade"
  fold: 0
  caption_column: 'report'
  train_path: 
  val_path: 
  test_path: 

num_classes: 6
lambda_param: 0.3

language: 
  model_type: ""
  base_dir: ""

vision:
  model_type: "LocalGlobalRegressionHIPT"
  config: ""
  model_weights: "../models/LocalGlobalHIPT_2048_768.pt"
  local_features_dir: ""
  


training:
    num_epochs: 10
    num_workers: 8
    batch_size: 1
    gradient_accumulation_steps: 16
    contrastive_loss: "triplet"
    classification_type: "single" #single or multi-label classification
    classification_loss: "mse"
    topk: 
      - 1
      - 5
      - 10
    loss_options:
        margin: 2.0
  

early_stopping:
  enable: False 
  patience: 5
  metric: "combined loss"
  min_epoch: 20
  mode: "min"
  save_all: False

optimizers:
  optim_vision:
      enable: True
      name: 'adamw'
      lr: 0.00001 
      wd: 0.001 
      lr_scheduler:
        name:  'step'
        step_size: 5
        gamma: 0.5


  optim_language:
    enable: False
    name: "adamw"
    lr: 
    wd: 
    lr_scheduler:
      name: 
      step_size: 
      gamma: 


wandb:
  enable: True
  project: 'contrastive_learning medical'
  username: ''
  exp_name: '${experiment_name}'
  tags: 
    - 'latest'
  dir: '/home/user'

  to_log:
    - 'train': ['contrastive loss', 'classification loss', 'combined loss', 'kappa', 'mean cosine similarity', 'retrieval kappa']
    - 'validation': ['contrastive loss', 'classification loss', 'combined loss', 'kappa', 'mean cosine similarity',  'retrieval kappa','retrieval top_1', 'retrieval top_5', 'retrieval top_10','cm']
    - 'test': ['contrastive loss', 'classification loss', 'combined loss', 'kappa', 'mean cosine similarity', 'cm','retrieval kappa','retrieval top_1', 'retrieval top_5', 'retrieval top_10']
  group:


  